zookeeper:
  image: ziyunhx/zookeeper
  ports: 
    - "49181:2181"
    - "22"
nimbus:
  image: ziyunhx/storm-nimbus:1.0.1
  ports:
    - "49773:3773"
    - "49772:3772"
    - "49627:6627"
    - "22"
  links: 
    - zookeeper:zk
supervisor:
  image: ziyunhx/storm-supervisor:1.0.1
  ports:
    - "8000"
    - "22"
  links: 
    - nimbus:nimbus
    - zookeeper:zk
ui:
  image: ziyunhx/storm-ui:1.0.1
  ports:
    - "49080:8080"
    - "22"
  links: 
    - nimbus:nimbus
    - zookeeper:zk
